server:
  port: 8081
spring:
  application:
    name: Products
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
integration:
  seller:
    url: http://localhost:8080
feign:
  connectionTimeout: 60000
  readTimeout: 60000